# Generated by Django 5.2.14 on 2026-05-15 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0002_alter_repository_id_alter_researchsession_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='researchsession',
            name='reasoning',
            field=models.TextField(blank=True, null=True),
        ),
    ]
